#driver name
TARGET = mpcdrv 


 

  obj-m  += mpcdrv.o
  # mpcdrv-objs := mpcdrvmain.o mpcdrvtest.o
  #Next step  add driver Cyclone3 PLIS <->P2020 driver exchange(взамен) mpcdrvlbcnor.o

  #mpcdrv-objs := pktgen.o
  #mpcdrv-objs := mpcdrvmain.o mpcdrvlbcnor.o mpcdrveth_ipv4.o mpcdrvtest.o
   mpcdrv-objs := mpcdrvmain.o mpcdrvlbcCyclone.o mpcdrveth_ipv4.o mpcdrvtest.o 
  

  
 #obj-m  += mpcdrv.o
 #obj-m  += mod.o 