#!/bin/sh

#
# set variables
#
DEV_NAME=mpcdev
DEV_MAX=4
MAJOR=`grep $DEV_NAME /proc/devices | cut -d ' ' -f 1`

#
# check if device driver is loaded
#
if [ -z "$MAJOR" ]; then
	echo "$DEV_NAME device driver not present - use 'modprobe $DEV_NAME"mod"'"
	exit 1
fi

#
# remove existing device files
#
rm -f /dev/$DEV_NAME*

#
# create new device files
#
for ((min = 0; min < $DEV_MAX; min = $[min+1]))
do
	mknod /dev/$DEV_NAME${min} c $MAJOR ${min}
done

#
# print result
#
ls -l /dev/$DEV_NAME*
